title = "Home | Atma seva "
baseURL = "https://www.atmaseva.co.uk/"
languageCode = "en-us"
theme = "airspace-hugo"

# The sites parameters
[params]
  home = " "
  
  [menu] 
    [[menu.header]]
      weight = 2
      name = "About us"
      url = "about-us"
    [[menu.header]]
      weight = 3
      name = "What we do"
      url = "whatwedo"
    [[menu.header]]
      weight = 4
      name = "Contact"
      url = "contact"
    [[menu.header]]
      weight = 5
      name = "Support"
      url = "donate"  
    [[menu.footer]]
      weight = 1
      name = "Home"
      url = "#"
    [[menu.footer]]
      weight = 2
      name = "About us"
      url = "about-us"
    [[menu.footer]]
      weight = 3
      name = "What we do"
      url = "whatwedo"
    [[menu.footer]]
      weight = 4
      name = "Contact"
      url = "contact"
    [[menu.footer]]
      weight = 5
      name = "Support"
      url = "donate"

  [params.wrapper]
      enable = true
      title = "Providing support, in Health care, Welfare and Education for Vulnerable, Marginalised, Women, Children and the Elderly in Uttarakhand, India"
      image = "img/aboutatma.jpg"

  [params.about]
    enable = true
    title = " "
    image = "img/aboutatma.jpg"
    
  [params.donate]
    enable = true
    title = "Support the SEVA"
    sub1 = " If you would like to contribute towards Atma Seva's efforts,"
    sub2 = " please do get in touch so we can send you the details. "
    email = "atmaseva108@gmail.com" 

  [params.blog]
    enable = false
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.contact]
    enable = true
    title = "Follow us on..." 
  [params.contact.box]
    title = "Email" 
    email = "atmaseva108@gmail.com"
    phone = "Phone: +88 01672 506 744"
     
